services:
  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: karasin
    ports:
      - "5432:5432"
    volumes:
      - karasin_pg:/var/lib/postgresql/data

volumes:
  karasin_pg:
